version: '3'
services:
  acron:
    image: funnyzak/alpine-cron:1.0.1
    privileged: false
    container_name: crons
    logging:
      driver: 'json-file'
      options:
        max-size: '1g'
    tty: true
    environment:
      - TZ=Asia/Shanghai
      - LANG=C.UTF-8
      - CRON_TAIL=1
      - CRON_STRINGS=* * * * * /scripts/echo.sh # excute every minute
    restart: on-failure
    volumes:
      - ./scripts:/scripts # cron scripts
      - ./cron:/etc/cron.d # more crontab files
      - ./logs:/logs # cron logs