version: '3'
services:
  acron:
    image: funnyzak/alpine-cron:1.0.1
    privileged: false
    container_name: crons
    logging:
      driver: 'json-file'
      options:
        max-size: '1g'
    tty: false
    environment:
      - TZ=Asia/Shanghai
      - LANG=C.UTF-8
      - CRON_TAIL=1
      - CRON_STRINGS=* * * * * /scripts/echo.sh # excute every minute
      - APP_NAME=TestCronApp
      - JISHIDA_TOKEN_LIST=jishidatoken
      - NOTIFY_URL_LIST=http://link1.com/notify1|http://link2.com/notify2
      - DINGTALK_TOKEN_LIST=dingtalktoken1|dingtalktoken2
      - IFTTT_HOOK_URL_LIST=https://maker.ifttt.com/trigger/cron_notify/with/key/ifttttoken-s3Up
    restart: on-failure
    volumes:
      - ./scripts:/scripts # cron scripts
      - ./cron:/etc/cron.d # more crontab files
      - ./logs:/logs # cron logs